### PR TITLE
Restructed File and Did Some Refix

### PR DESCRIPTION
**Pull request by Qudusayo**
- Moved all styling files to a style folder
- Restructured styling folder to scss
- Removing bootstrap for full-fledged design
- No downgrade in design, but new standard set for full-fledged design

### CODE REVIEW

**Comment by Qudusayo** [comment]
Also moved the font family to [Rubik](https://fonts.google.com/specimen/Rubik?query=Rubik) which seems interesting.

**Comment by abdulloooh** [comment]
can you please reopen this pr, probably push again and start a new pr but now to development @Qudusayo 
please

**Comment by Qudusayo** [comment]
Okay.
I'll push again, but on another branch and I should make a PR to master branch rather ?

**Comment by abdulloooh** [comment]
to development branch please

**Comment by abdulloooh** [comment]
i dont think it's needed anymore, since it already got merged with https://github.com/abdulloooh/sanwo/pull/8

This is what I realized,
when I switched the base to development, all of your push after was automatically added to the pr; I guess that's why you were not able to create another to pr to development then but only to master.

So when I merged the pr to development, it already include all other updates in this pr too.
I hope that makes sense

**Comment by abdulloooh** [comment]
I tried to compare the current status of Qudusao/qudusayo currently with abdulloooh/sanwo/development and it shows there is now difference so we are cool.

If you can please help to change that stock image to anything else that is also good as per our discussion so I can merge into master and deploy

**Pull request merged**
